
# Change path to intermediate location
calibrations_main_dir: "outputs/post_validation_round/calibrations"
output_dir: "outputs/post_validation_round/projections"

## -()- Quick test runs
#use_location_ids: ["AC", "SP"]
#use_projection_years: [2022, 2023]  # For testing
#ncpus: 1
#calibrations_main_dir: "outputs/quick_test_runs/calibrations"  # -()- Take from quick test as well
#output_dir: "outputs/quick_test_runs"

# -()- Full run
use_location_ids: []
use_projection_years: [2022, 2023, 2024, 2025]
ncpus: 12

## -()- Alternative 01: Add outbreak features likelihood temperature
#ll_temperature: 0.2
#output_dir: "outputs/sensitivity/outb_feats_ll_temperature_v01"

## -()- Alternative 02: Higher number of projection simulations (ACCEPTED AS DEFAULT)
#num_projection_samples: 5000
#output_dir: "outputs/sensitivity/change_post_sample_size_01"


## -()- Sensitivity: No update from outbreak features
#use_location_ids: []
#use_projection_years: [2022, 2023, 2024, 2025]
#ncpus: 6
#output_dir: "outputs/sensitivity/no_update_from_outbreak_features"
#outbreak_feature_names: []  # No outbreak features considered


exclude_years_by_location:
  ES: [2021,]  # 2021: Absent cases in data
  # --- Extra years spotted on final revision
  AL: [2015,]  # Bad fit due to late peak last season ("contaminated" scaling factor prior)
  PI: [2021,]  # Extremely wide CI on calibration
  SE: [2018,]  # Calibration got artificially early season end, bad fit after peak


#outbreak_features_predictions_dir: "outputs/outbreak_features_mockup"  # Use mockup dir
outbreak_features_predictions_dir: "predictions"  # Use separate `predictions` dir for now
#outbreak_feature_names: [  # Select which outbreak features are used to update distributions. Use default otherwise.
#  "peak_week",
#]
