
# Change path to intermediate location
output_dir: "outputs/post_validation_round/projections"

# # -()- Quick test runs
#use_location_ids: ["AC", "SP"]
#use_projection_years: [2022, 2023]
#ncpus: 1
#output_dir: "outputs/quick_test_runs"

# -()- Full runs
use_location_ids: []
use_projection_years: [2022, 2023, 2024, 2025]
ncpus: 12

## -()- Alternative 01: Add outbreak features likelihood temperature
#output_dir: "outputs/sensitivity/outb_feats_ll_temperature_v01"

## -()- Alternative 02: Higher number of projection simulations
#output_dir: "outputs/sensitivity/change_post_sample_size_01"

## -()- Sensitivity: No update from outbreak features
#use_location_ids: []
#use_projection_years: [2022, 2023, 2024, 2025]
#ncpus: 6
#output_dir: "outputs/sensitivity/no_update_from_outbreak_features"
